enum MySharedKeys {
  firstOpen,
  currentLanguage,
  language,
  apiToken,
  name,
  picture,
  email,
  phone,
  preferredPickupTimes,
  preferredPickupTimesV2,
  cancellationReasons,
  buyForMeCategories,
  maxDimensions,
  maxWeight,
  orderCategories,
  canSendPackage,
  canBuyForMe,
  canMoveAndTransfer,
  userId,
  lastName,
  firstName,
  userName,
  defaultAddressId, city, addressDetails,
}
